# Generated by Django 5.0 on 2024-01-24 05:56

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DisabilityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "categories",
                    models.CharField(
                        choices=[
                            ("a", "Categories A"),
                            ("b", "Categories B"),
                            ("c", "Categories C"),
                            ("d", "Categories D"),
                            ("e", "Categories E"),
                            ("o", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "disableimg",
                    models.ImageField(
                        default="default_course.jpg", upload_to="disable_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "industry_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="company_logos/"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "profileimg",
                    models.ImageField(
                        default="blank-profile-pic.png", upload_to="profile_images"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", ckeditor.fields.RichTextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courseimg",
                    models.ImageField(
                        default="default_course.jpg", upload_to="courses_images/"
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disability_types",
                    models.ManyToManyField(
                        blank=True, related_name="courses", to="usa.disabilitytype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Blogs",
            fields=[
                ("title", models.CharField(max_length=100)),
                ("id_blog", models.AutoField(primary_key=True, serialize=False)),
                ("abstraction", models.TextField(blank=True, max_length=250)),
                (
                    "categories",
                    models.CharField(
                        choices=[
                            ("inspiration", "Inspiration"),
                            ("interviews", "Interviews"),
                            ("stories", "Stories"),
                            ("prepration", "Prepration"),
                            ("resources", "Resources"),
                            ("experience", "Experience"),
                            ("awareness", "Awareness"),
                            ("research", "Research"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "tumbnail",
                    models.ImageField(
                        default="default_blogs.jpg", upload_to="blogs_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disability_types",
                    models.ManyToManyField(
                        blank=True, related_name="blogs", to="usa.disabilitytype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                ("job_title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("design", "Design"),
                            ("development", "Development"),
                            ("customer", "Customer"),
                            ("health_caare", "Health and Caare"),
                            ("automotive", "Automotive jobs"),
                            ("data_entry", "Data entry"),
                            ("call_center", "Call center"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("hibrid", "Hibrid"),
                            ("remote", "Remote"),
                            ("wfo", "WFO"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("internship", "Internship"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "categories",
                    models.CharField(
                        choices=[("government", "Government"), ("private", "Private")],
                        max_length=10,
                    ),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hours", models.PositiveIntegerField()),
                ("about", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_date", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("is_closed", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        default="D:\\main_usa_app\\main_usa_app\\main_usa_app\\main_usa_app\\main_usa_app\\main_usa_app\\media\\default_job_banner.jpg",
                        upload_to="job_images/",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="usa.company",
                    ),
                ),
                (
                    "disability_types",
                    models.ManyToManyField(
                        blank=True, related_name="jobs", to="usa.disabilitytype"
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="disabilitytype",
            name="job_opportunities",
            field=models.ManyToManyField(blank=True, to="usa.job"),
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usa.job"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSeeker",
            fields=[
                ("username", models.TextField(max_length=30)),
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("bio", models.TextField(blank=True)),
                (
                    "profileimg",
                    models.ImageField(
                        default="blank-profile-pic.png", upload_to="profile_images/"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("dob", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("udid", models.CharField(blank=True, max_length=50)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("about", models.CharField(blank=True, max_length=500)),
                ("dis_type", models.CharField(max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_url", models.URLField()),
                ("description", ckeditor.fields.RichTextField()),
                ("sequence_order", models.PositiveIntegerField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="usa.courses",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaveJobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="usa.job"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
