# Generated by Django 5.0 on 2023-12-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(
                default="D:\\main_usa_app\\main_usa_app\\main_usa_app\\media\\default_job_banner.jpg",
                upload_to="job_images/",
            ),
        ),
    ]
