# Generated by Django 5.0 on 2024-01-24 06:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="company",
        ),
        migrations.AddField(
            model_name="job",
            name="company_description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="company_name",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
