# Generated by Django 5.0 on 2024-01-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0003_delete_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="company_description",
        ),
        migrations.RemoveField(
            model_name="job",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="job",
            name="url",
        ),
    ]
