# Generated by Django 5.0 on 2023-12-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0003_remove_job_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="id",
        ),
        migrations.AddField(
            model_name="job",
            name="categories",
            field=models.CharField(
                choices=[("government", "Government"), ("private", "Private")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="job_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="mode",
            field=models.CharField(
                choices=[("hibrid", "Hibrid"), ("remote", "Remote"), ("wfo", "WFO")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="time",
            field=models.CharField(
                choices=[("full_time", "Full Time"), ("part_time", "Part Time")],
                default=12,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("marketing", "Marketing"),
                    ("design", "Design"),
                    ("development", "Development"),
                    ("customer", "Customer"),
                    ("health_caare", "Health and Caare"),
                    ("automotive", "Automotive jobs"),
                    ("data_entry", "Data entry"),
                    ("call_center", "Call center"),
                ],
                max_length=20,
            ),
        ),
    ]
