# Generated by Django 5.0 on 2023-12-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0004_remove_job_id_job_categories_job_job_id_job_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="time",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("internship", "Internship"),
                ],
                max_length=10,
            ),
        ),
    ]
