# Generated by Django 5.0 on 2024-01-24 17:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0005_companies_job_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="is_closed",
        ),
        migrations.RemoveField(
            model_name="job",
            name="timestamp",
        ),
        migrations.AlterField(
            model_name="job",
            name="about",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
