# Generated by Django 5.0 on 2023-12-16 03:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0006_contributor_jobseeker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="about",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
