# Generated by Django 5.0 on 2024-01-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0006_remove_job_is_closed_remove_job_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companies",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
