# Generated by Django 5.0 on 2024-01-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0007_companies_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
