# Generated by Django 5.0 on 2023-12-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0008_savejobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseeker",
            name="profileimg",
            field=models.ImageField(
                default="blank-profile-pic.png", upload_to="profile_images/"
            ),
        ),
    ]
