# Generated by Django 5.0 on 2024-01-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0008_job_is_closed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(
                default="default_job_banner.png", upload_to="job_images/"
            ),
        ),
    ]
