# Generated by Django 5.0 on 2023-12-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0010_disabilitytype_courses_lecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="profileimg",
            field=models.ImageField(
                default="default_course.jpg", upload_to="courses_images/"
            ),
        ),
    ]
