# Generated by Django 5.0 on 2024-01-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0010_alter_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="email",
            field=models.EmailField(default="default.email@gmail.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicant",
            name="name",
            field=models.CharField(default="User", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="applicant",
            name="resume",
            field=models.FileField(blank=True, upload_to="applicant_resumes/"),
        ),
    ]
