# Generated by Django 5.0 on 2023-12-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0011_courses_profileimg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courses",
            old_name="profileimg",
            new_name="courseimg",
        ),
    ]
