# Generated by Django 5.0 on 2023-12-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0012_rename_profileimg_courses_courseimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="disability_types",
            field=models.ManyToManyField(
                blank=True, related_name="jobs", to="usa.disabilitytype"
            ),
        ),
    ]
