# Generated by Django 5.0 on 2023-12-18 16:20

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0013_job_disability_types"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="about",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="Blogs",
            fields=[
                ("id_blog", models.AutoField(primary_key=True, serialize=False)),
                ("abstraction", models.TextField(blank=True, max_length=250)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "tumbnail",
                    models.ImageField(
                        default="default_blogs.jpg", upload_to="blogs_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "disability_types",
                    models.ManyToManyField(
                        blank=True, related_name="blogs", to="usa.disabilitytype"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
