# Generated by Django 5.0 on 2023-12-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0014_alter_job_about_blogs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseeker",
            name="skills",
        ),
        migrations.AddField(
            model_name="jobseeker",
            name="username",
            field=models.TextField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
