# Generated by Django 5.0 on 2023-12-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0015_remove_jobseeker_skills_jobseeker_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="title",
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
