# Generated by Django 5.0 on 2023-12-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0017_alter_blogs_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="disabilitytype",
            name="job_opportunities",
            field=models.ManyToManyField(blank=True, to="usa.job"),
        ),
    ]
