# Generated by Django 5.0 on 2023-12-19 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0018_disabilitytype_job_opportunities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disabilitytype",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
