# Generated by Django 5.0 on 2023-12-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0019_alter_disabilitytype_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="disabilitytype",
            name="disableimg",
            field=models.ImageField(
                default="default_course.jpg", upload_to="disable_images/"
            ),
        ),
    ]
