# Generated by Django 5.0 on 2023-12-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0020_disabilitytype_disableimg"),
    ]

    operations = [
        migrations.AddField(
            model_name="disabilitytype",
            name="categories",
            field=models.CharField(
                choices=[
                    ("a", "Categories A"),
                    ("b", "Categories B"),
                    ("c", "Categories C"),
                    ("d", "Categories D"),
                    ("e", "Categories E"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
