# Generated by Django 5.0 on 2024-01-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0021_disabilitytype_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disabilitytype",
            name="categories",
            field=models.CharField(
                choices=[
                    ("a", "Categories A"),
                    ("b", "Categories B"),
                    ("c", "Categories C"),
                    ("d", "Categories D"),
                    ("e", "Categories E"),
                    ("o", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="image",
            field=models.ImageField(
                default="D:\\main_usa_app\\main_usa_app\\main_usa_app\\main_usa_app\\main_usa_app\\main_usa_app\\media\\default_job_banner.jpg",
                upload_to="job_images/",
            ),
        ),
    ]
