# Generated by Django 5.0 on 2024-01-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usa", "0022_alter_disabilitytype_categories_alter_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="categories",
            field=models.CharField(
                choices=[
                    ("inspiration", "Inspiration"),
                    ("interviews", "Interviews"),
                    ("stories", "Stories"),
                    ("prepration", "Prepration"),
                    ("resources", "Resources"),
                    ("experience", "Experience"),
                    ("awareness", "Awareness"),
                    ("research", "Research"),
                    ("other", "Other"),
                ],
                default=9,
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
